# Generated by Django 5.0.1 on 2024-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
